# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946036a0f39389e7192853e4f726731010905627f853a6c3983d4ef3521d0f746b71517ccb7de0c10c358d931a0fdcda68295d92ebd8e95841be5729e766bd6c

test:
  secret_key_base: 3402af4ea4d399477741a456ed152e306c85b759f946b3351b7598152924a6e29d4f728e00e52565aee93574bc213e6f37b1c8a78fb038d096e232b69f686421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
