require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FrGramsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FrGram. As you add validations to FrGram, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FrGramsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all fr_grams as @fr_grams" do
      fr_gram = FrGram.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fr_grams)).to eq([fr_gram])
    end
  end

  describe "GET #show" do
    it "assigns the requested fr_gram as @fr_gram" do
      fr_gram = FrGram.create! valid_attributes
      get :show, {:id => fr_gram.to_param}, valid_session
      expect(assigns(:fr_gram)).to eq(fr_gram)
    end
  end

  describe "GET #new" do
    it "assigns a new fr_gram as @fr_gram" do
      get :new, {}, valid_session
      expect(assigns(:fr_gram)).to be_a_new(FrGram)
    end
  end

  describe "GET #edit" do
    it "assigns the requested fr_gram as @fr_gram" do
      fr_gram = FrGram.create! valid_attributes
      get :edit, {:id => fr_gram.to_param}, valid_session
      expect(assigns(:fr_gram)).to eq(fr_gram)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FrGram" do
        expect {
          post :create, {:fr_gram => valid_attributes}, valid_session
        }.to change(FrGram, :count).by(1)
      end

      it "assigns a newly created fr_gram as @fr_gram" do
        post :create, {:fr_gram => valid_attributes}, valid_session
        expect(assigns(:fr_gram)).to be_a(FrGram)
        expect(assigns(:fr_gram)).to be_persisted
      end

      it "redirects to the created fr_gram" do
        post :create, {:fr_gram => valid_attributes}, valid_session
        expect(response).to redirect_to(FrGram.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved fr_gram as @fr_gram" do
        post :create, {:fr_gram => invalid_attributes}, valid_session
        expect(assigns(:fr_gram)).to be_a_new(FrGram)
      end

      it "re-renders the 'new' template" do
        post :create, {:fr_gram => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fr_gram" do
        fr_gram = FrGram.create! valid_attributes
        put :update, {:id => fr_gram.to_param, :fr_gram => new_attributes}, valid_session
        fr_gram.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fr_gram as @fr_gram" do
        fr_gram = FrGram.create! valid_attributes
        put :update, {:id => fr_gram.to_param, :fr_gram => valid_attributes}, valid_session
        expect(assigns(:fr_gram)).to eq(fr_gram)
      end

      it "redirects to the fr_gram" do
        fr_gram = FrGram.create! valid_attributes
        put :update, {:id => fr_gram.to_param, :fr_gram => valid_attributes}, valid_session
        expect(response).to redirect_to(fr_gram)
      end
    end

    context "with invalid params" do
      it "assigns the fr_gram as @fr_gram" do
        fr_gram = FrGram.create! valid_attributes
        put :update, {:id => fr_gram.to_param, :fr_gram => invalid_attributes}, valid_session
        expect(assigns(:fr_gram)).to eq(fr_gram)
      end

      it "re-renders the 'edit' template" do
        fr_gram = FrGram.create! valid_attributes
        put :update, {:id => fr_gram.to_param, :fr_gram => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested fr_gram" do
      fr_gram = FrGram.create! valid_attributes
      expect {
        delete :destroy, {:id => fr_gram.to_param}, valid_session
      }.to change(FrGram, :count).by(-1)
    end

    it "redirects to the fr_grams list" do
      fr_gram = FrGram.create! valid_attributes
      delete :destroy, {:id => fr_gram.to_param}, valid_session
      expect(response).to redirect_to(fr_grams_url)
    end
  end

end
